version: '3.7'

services:
  cli:
    container_name: cli
    privileged: true
    build: ./cli/
    image: cli
    volumes:
      - ./data:/usr/src/app/data
    network_mode: host
  nmap:
    container_name: nmap
    privileged: true
    build: ./nmap/
    image: nmap
    volumes:
      - ./data:/usr/src/app/data
    network_mode: host
  firmware:
    container_name: firmware
    privileged: true
    build: ./firmware/
    image: firmware
    volumes:
      - ./data:/usr/src/app/data
    network_mode: host
  firmwalker:
    container_name: firmwalker
    privileged: true
    build: ./firmwalker/
    image: firmwalker
    volumes:
      - ./data:/usr/src/app/firmware_data
    network_mode: host
  web:
    container_name: web
    privileged: true
    build: ./web/
    image: web
    ports:
      - 9090:9090
    volumes:
      - ./data:/data
    environment:
      TFM_DATA: ${TFM_DATA:-/data}
  traffic:
    container_name: traffic
    privileged: true
    build: ./traffic/
    image: traffic
    volumes:
      - ./data:/usr/src/app/data
    network_mode: host
  directories:
    container_name: directories
    build: ./directories/
    image: directories
    volumes:
      - ./data/dir:/usr/src/app/data
    network_mode: host
  testssl:
    container_name: testssl
    build: ./testssl/
    image: testssl
    volumes:
      - ./data:/home/testssl/data
    network_mode: host
